---

- name: Make sure we have a 'wheel' group
  group:
    name: wheel
    state: present


- name: Allow 'wheel' group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%wheel'
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    validate: 'visudo -cf %s'


- name: Create users
  user:
    name: "{{ item }}"         
    groups: docker, wheel
    append: yes 
    state: present
    create_home: yes
  with_items: "{{ required_users }}"


- name: Add SSH public keys for users
  authorized_key:
    user: "{{ item }}"
    state: present
    key: "{{ lookup('file', 'mykey_rsa.pub') }}"
  with_items: "{{ required_users }}"
